# Generated by Django 4.0.3 on 2022-04-01 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_images',
            field=models.CharField(default='https://cdn3.f-cdn.com/contestentries/1287460/28855021/5ab5583ddaadd_thumb900.jpg', max_length=255),
        ),
    ]
